name: Prod build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Build NPM Package
      uses: actions/npm@master
      with:
        args: run build

    - name: Deploy to NPM
      uses: actions/npm@master
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      with:
        args: publish --access public
