name: Prod build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Deploy to NPM
      uses: actions/npm@master
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      with:
        args: publish --access public
